PortfolioLab/urls.py
from django.contrib import admin
from django.urls import path

from oddam_app.views import LandingPageView, AddDonationView, LoginView, RegisterView, FormView, LogoutView,\
    ProfileView, UserDonationsView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('add_donation/', AddDonationView.as_view(), name='add-donation'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('form/', FormView.as_view(), name='form'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_donations/', UserDonationsView.as_view(), name='user-donations'),
]

oddam_app/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, password2, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('Email musi być ustawiony'))
        if password != password2:
            raise ValidationError('Hasła nie są takie same')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


TYPES = (
    (1, 'fundacja'),
    (2, 'organizacja pozarządowa'),
    (3, 'zbiórka lokalna'),
)


class Category(models.Model):
    name = models.CharField(max_length=128)


class Institution(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    type = models.CharField(choices=TYPES, default=1, max_length=128)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=128)
    phone_number = models.IntegerField()
    city = models.CharField(max_length=64)
    zip_code = models.CharField(max_length=64)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.TextField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, default=None)

oddam_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View

from .models import Donation, Institution, CustomUser, Category


class LandingPageView(View):
    def get(self, request):
        bag_counter = 0
        institution_counter = 0
        fundacje = Institution.objects.filter(type='fundacja')
        organizacje = Institution.objects.filter(type='organizacja pozarządowa')
        zbiorki = Institution.objects.filter(type='zbiórka lokalna')
        donations = Donation.objects.all()
        institution_id_list = []
        counter_list = []
        for donation in donations:
            bag_counter += donation.quantity
            if donation.institution_id:
                institution_id_list.append(donation.institution_id)
        for _ in institution_id_list:
            if _ not in counter_list:
                institution_counter += 1
                counter_list.append(_)

        return render(request, 'index.html', {
            'bag_counter': bag_counter,
            'institution_counter': institution_counter,
            'fundacje': fundacje,
            'organizacje': organizacje,
            'zbiorki': zbiorki,
                                              })


class AddDonationView(View):
    def get(self, request):
        return render(request, 'form.html')


class LoginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        user = authenticate(email=request.POST.get('email'), password=request.POST.get('password'))
        if user:
            login(request, user)
            return redirect('/')
        return redirect('register')


class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        first_name = request.POST.get('name')
        last_name = request.POST.get('surname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        CustomUser.objects.create_user(first_name=first_name, last_name=last_name, email=email, password=password, password2=password2)
        return redirect('login')


class FormView(View):
    def get(self, request):
        if request.user.is_authenticated:
            categories = Category.objects.all()
            institutions = Institution.objects.all()
            return render(request, 'form.html', {'categories': categories, 'institutions': institutions})
        else:
            return redirect('login')

    def post(self, request):
        bags = request.POST["bags"]
        address = request.POST["address"]
        phone = int(request.POST["phone"])
        city = request.POST["city"]
        postcode = request.POST["postcode"]
        date = request.POST["date"]
        time = request.POST["time"]
        more_info = request.POST["more_info"]
        institution_id = request.POST["institution_id"]
        categories_id = request.POST["categories_id"]
        donation = Donation.objects.create(
            quantity=bags,
            address=address,
            phone_number=phone,
            city=city,
            zip_code=postcode,
            pick_up_date=date,
            pick_up_time=time,
            pick_up_comment=more_info,
            institution_id=institution_id,
            user=request.user
        )
        categories = categories_id.split(',')
        for category in categories:
            donation.categories.add(Category.objects.get(pk=int(category)))
        return render(request, 'form-confirmation.html')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('landing-page')


class ProfileView(View):
    def get(self, request):
        if request.user.is_authenticated:
            current_user = request.user
            return render(request, 'profile.html', {'current_user': current_user})
        return render(request, 'profile.html')


class UserDonationsView(View):
    def get(self, request):
        if request.user.is_authenticated:
            current_user = request.user
        return render(request, 'user-donations.html', {'current_user': current_user})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
  </head>
<body>
{% block content %}

{% endblock %}

    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form>
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"><img src="{% static 'images/icon-facebook.svg' %}"/></a>
          <a href="#" class="btn btn--small"><img src="{% static 'images/icon-instagram.svg' %}"/></a>
        </div>
      </div>
    </footer>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/form-confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <header class="header--form-page">
      {% include 'form_nav.html' %}

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>




{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <header class="header--form-page">
      {% include 'form_nav.html' %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form action="" id="form-js" method="post">
        {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>
            {% for category in categories %}
            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value={{ category.pk }}
                />
                <span class="checkbox"></span>
                <span id="category-span" class="description"
                  >{{ category.name }}</span
                >
              </label>
            </div>
            {% endfor %}


            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 3 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>

            <div class="form-group form-group--checkbox">
                {% for institution in institutions %}
              <label>
                <input type="radio" name="organization" value="{{ institution.pk }}" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">{{ institution.get_type_display }} “{{ institution.name }}”</div>
                  <div class="subtitle">
                    Cel i misja: {{ institution.description}}
                  </div>
                </span>
              </label>
                {% endfor %}
            </div>



            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text" id="BAG"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text" id="INST"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul id="UL1">
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul id="UL2">
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>



{% endblock %}

templates/form_nav.html
<nav class="container container--70">
        <ul class="nav--actions">
          <li class="logged-user">
              {% if user.is_authenticated %}
                Witaj {{ user.first_name }}
              {% else %}
                Witaj Agata
              {% endif %}
            <ul class="dropdown">
              <li><a href="{% url 'profile' %}">Profil</a></li>
                <li><a href="#">Ustawienia</a></li>
              <li><a href="{% url 'user-donations' %}">Moje zbiórki</a></li>
                {% if user.is_superuser %}
                    <li><a href="/admin/">panel administracyjny</a></li>
                {% endif %}
              <li><a href="{% url 'logout' %}">Wyloguj</a></li>
            </ul>
          </li>
        </ul>

        <ul>
          <li><a href="{% url 'landing-page' %}" class="btn btn--without-border active">Start</a></li>
          <li><a href="{% url 'landing-page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="{% url 'landing-page' %}#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="{% url 'landing-page' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            <li><a href="{% url 'form' %}" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="{% url 'landing-page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <header class="header--main-page">
      <nav class="container container--70">
        <ul class="nav--actions">
          <li><a href="{% url 'login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a href="{% url 'register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>

        <ul>
          <li><a href="" class="btn btn--without-border active">Start</a></li>
          <li><a href="#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="{% url 'form' %}" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
    </header>

    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>{{ bag_counter }}</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>{{ institution_counter }}</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="{% url 'register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="{% static 'images/signature.svg' %}" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="{% static 'images/about-us.jpg' %}" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->
      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>
        {% for i in fundacje %}
            <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ i.get_type_display }} "{{ i.name }}"</div>
              <div class="subtitle">Cel i misja: {{ i.description }}</div>
            </div>

            <div class="col"><div class="text">
                {% for category in i.categories.all %}
                {{ category.name }},
            {% endfor %}
            </div></div>
          </li>
            </ul>
          {% endfor %}

      <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
        </ul>
        -->

      </div>


      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
          quos suscipit corporis!
        </p>
        {% for i in organizacje %}
            <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ i.get_type_display  }} "{{ i.name }}"</div>
              <div class="subtitle">Cel i misja: {{ i.description }}</div>
            </div>

            <div class="col"><div class="text">
                {% for category in i.categories.all %}
                {{ category.name }},
            {% endfor %}
            </div></div>
          </li>
            </ul>
          {% endfor %}

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
        </ul>
        -->
      </div>

      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
       {% for i in zbiorki %}
            <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ i.get_type_display  }} "{{ i.name }}"</div>
              <div class="subtitle">Cel i misja: {{ i.description }}</div>
            </div>

            <div class="col"><div class="text">
                {% for category in i.categories.all %}
                {{ category.name }},
            {% endfor %}
            </div></div>
          </li>
            </ul>
          {% endfor %}

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
        </ul>
        -->
      </div>
    </section>


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'lr_header.html' %}

    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form method="post" action="">
          {% csrf_token %}
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>

{% endblock %}

templates/lr_header.html
<header>
      <nav class="container container--70">
        <ul class="nav--actions">
          <li><a href="{% url 'login' %}">Zaloguj</a></li>
          <li class="highlighted"><a href="{% url 'register' %}">Załóż konto</a></li>
        </ul>

        <ul>
          <li><a href="{% url 'landing-page' %}">Start</a></li>
          <li><a href="{% url 'landing-page' %}#steps">O co chodzi?</a></li>
          <li><a href="{% url 'landing-page' %}#about-us">O nas</a></li>
          <li><a href="{% url 'landing-page' %}#help">Fundacje i organizacje</a></li>
          <li><a href="#contact">Kontakt</a></li>
        </ul>
      </nav>
    </header>

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="justify-content: center; background-color: silver">
    <h2 style="color: crimson"><b>Profil użytkownika</b></h2>
        <h2>Imię: {{ current_user.first_name }}</h2>
        <h2>Nazwisko: {{ current_user.last_name }}</h2>
        <h2>Email: {{ current_user.email }}</h2>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'lr_header.html' %}

    <section class="login-page">
      <h2>Załóż konto</h2>
      <form method="post" action="">
          {% csrf_token %}
        <div class="form-group">
          <input type="text" name="name" placeholder="Imię" />
        </div>
         <div class="form-group">
          <input type="text" name="surname" placeholder="Nazwisko" />
        </div>
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
        </div>
        <div class="form-group">
          <input type="password" name="password2" placeholder="Powtórz hasło" />
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'login' %}" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>

{% endblock %}

templates/user-donations.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="justify-content: center; background-color: silver">
    <h2 style="color: rosybrown"><b>Przekazane dary użytkownika {{ current_user.first_name }}:</b></h2>
    <ul>
        {% for donation in current_user.donation_set.all %}
            <li>Id transakcji: {{ donation.pk }}</li>
            <li>Ilość worków: {{ donation.quantity }}</li>
            <li>Dla: {{ donation.institution.name }}</li>
            <li>Zawartość: {% for category in donation.categories.all %}
                    {{ category.name }}
                {% endfor %}
                </li>
            <li>Odbiór: {{ donation.pick_up_date }}</li>
            <li>Godzina odbioru: {{ donation.pick_up_time }}</li>
            <hr style="color: crimson">
        {% endfor %}
    </ul>

</div>
{% endblock %}